openapi: '3.0.3'
info:
  title: Partner API
  version: '1.0'
servers:
  - url: https://api.predic8.de/v1
paths:
  /partners:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                name:
                  type: string
                  example: Max Maier
                year:
                  type: integer
                  minimum: 18
      responses:
        '201':
          description: Created 

    
