openapi: '3.0.3'
info:
  title: The Partner API
  version: '1.1'
servers:
  - url: https://api.predic8.de/partner/v1
paths:
  /partners:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                name:
                  type: string
                  example: Max Maier
                  minLength: 5
                  maxLength: 100
                year:
                  type: integer
                  minimum: 18
                  maximum: 99
      responses:
        '201':
          description: Created 

    
